# Generated by Django 5.1.6 on 2025-03-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('audio_file', models.FileField(upload_to='tts/')),
                ('conversion_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
