# Generated by Django 5.1.6 on 2025-03-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionhistory',
            name='file_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
